### ISSUE TITLE
1.0.3 Is broken

### ISSUE THREAD

**Issue by fancycoconut** [yKanazawa/sendgrid-maildev#7]
Hi,
It looks like version 1.0.3 is broken where the sendgrid-dev-api fails to start in the container:

https://hub.docker.com/r/ykanazawa/sendgrid-maildev/tags

**Comment by yKanazawa** [comment]
Thank you for report.
I'm sorry that I was not aware of it.

This may be due to a minor upgrade of the OS.
1.0.4 has already been released.

I thought It is not a good idea to latast the OS tag.
